### ISSUE TITLE
Error processing or transcribing Bazarr audio_file: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by KurtVanHove** [McCloudS/subgen#146] opened 2024-12-02 00:31 UTC
Hi,

Running subgen (latest) with bazarr (1.4.5) here.
I receive (both on ubuntu 22.04 and on Windows) an error when Bazarr is making a request: 

UnboundLocalError: local variable 'language_code' referenced before assignment
File subgen.py, line 443, in detect_language
line: return { "detected_language": detected_language, "language_code": language_code }

It does detect the language (Detected Language: english)
The error occurs afterwards: Error processing or transcribing Bazarr audio_file: 'NoneType' object has no attribute 'items'.
This last may trigger the catch in the try-catch (I'm new to python), which gives the UnboundLocalError 

my python version = 3.10.12

So the problem is two-fold: 
* the UnboundLocalError can maybe be handled with a default assignment of language_code in the "finally" part, now it kind of steered me in the wrong direction to look for a solution :)
* there's probably something wrong with my setup, or maybe even Bazarr-requests in general, which is causing these NoneType errors.

**Comment by muisje** [comment] 2024-12-02 00:42
Hey, I made some changes to the code and it appears I was not thorough enough with my testing. Anyways the problem is probably that the audio file doesn't have the property of language set or something. I'll fix it tomorrow. Perdon for the problematic update to the code. It's not you. You can use an older version before my pull request was merged.

**Comment by McCloudS** [comment] 2024-12-02 01:16
Just pushed a fix and it appears to be working on my instance.  You can pull the new subgen.py.

**Closed** 2024-12-02 01:19 UTC

**Comment by KurtVanHove** [comment] 2024-12-02 08:28
No worries, thanks for doing this project & thanks again for the quick follow-up.
The error seems to be gone.
